version: '2'
services:
  tdd:
    build:
      context: .
    container_name: tdd
    environment:
      - SECRET_KEY=secret
      - EMAIL_PASSWORD=123
    volumes:
      - ./database:/database
      - ./static:/static
    ports:
      - "8000:8000"
